// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQW2XvfLEEbL1W_D9h4ki_6MSw9vKOCkY',
    appId: '1:471207975685:web:93ab997bb42f8e5b07756c',
    messagingSenderId: '471207975685',
    projectId: 'jwh-001',
    authDomain: 'jwh-001.firebaseapp.com',
    storageBucket: 'jwh-001.firebasestorage.app',
    measurementId: 'G-NTX24LG86C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyB1QSQfdT1ZAK3_Byvu6gZfMcQnsuI1g',
    appId: '1:471207975685:android:f47665b24a6bebdd07756c',
    messagingSenderId: '471207975685',
    projectId: 'jwh-001',
    storageBucket: 'jwh-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vd6A9P2byQszm0UnfhZOfXtz4s9D2Xc',
    appId: '1:471207975685:ios:4c6d4158d1a0102a07756c',
    messagingSenderId: '471207975685',
    projectId: 'jwh-001',
    storageBucket: 'jwh-001.firebasestorage.app',
    iosBundleId: 'com.omiz.jwh01',
  );

}